name: production-deploy
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: git submodule update --init --recursive
      - run: echo "a new test line" > ../submodule-two/index.html